### ISSUE TITLE
El philip no vino a la U

### ISSUE THREAD

**Issue by acifuentes99** [dinga99/arandano#1]
Solucionar lo antes posible, se perdio una empanada gratis

**Comment by felipeavaria** [comment]
Jajajja critico! ;(

**Comment by felipeavaria** [comment]
Jajajja critico! ;(

**Comment by acifuentes99** [comment]
a partir de la otra semana hay que arreglar el bug :v . Ya en verdad hay que poner cosas serias antes que la ayudante vea esto, si no es mala practica xD (lo sacare a la noche)

**Comment by CatherinVargas** [comment]
Ya lo ví -.- llegan correos además
